user: promadm
app_root_dir: "/app/prometheus2.51.1"
prom_source_url: "https://github.com/prometheus/prometheus/releases/download/v2.51.2/prometheus-2.51.2.linux-amd64.tar.gz"
prom_archive_dest: "/tmp/prometheus-2.51.2.linux-amd64.tar.gz"
prom_tmp_dir: "/tmp/prometheus-2.51.2"