---
- name: Install required packages
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - gnupg2
    - apt-transport-https
    - software-properties-common
    - wget
    
- name: Download Grafana GPG key
  get_url:
    url: https://packages.grafana.com/gpg.key
    dest: "{{ graf_tmp_dir }}/grafana.key"
    mode: 'u=rwx,go=r'

- name: Add Grafana GPG key
  ansible.builtin.shell: "cat {{ graf_tmp_dir }}/grafana.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/grafana.gpg >/dev/null"

- name: Add Grafana repository
  ansible.builtin.shell: "echo 'deb [signed-by=/etc/apt/trusted.gpg.d/grafana.gpg] https://packages.grafana.com/oss/deb stable main' | sudo tee /etc/apt/sources.list.d/grafana.list"

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install Grafana
  ansible.builtin.apt:
    name: grafana
    state: present

- name: Backup original Grafana configuration
  ansible.builtin.shell: "cp /etc/grafana/grafana.ini /etc/grafana/grafana.ini.backup"
  
- name: Modifier les lignes commentées dans le fichier de configuration Grafana
  ansible.builtin.lineinfile:
    path: "{{ graf_ini_file }}"
    regexp: '^;({{ item.key }})\s*=\s*(.*)'
    line: '{{ item.key }} = {{ item.value }}'
    state: present
  loop: "{{ graf_ini_config }}"

- name: Restart Grafana service
  ansible.builtin.systemd:
    name: grafana-server
    state: restarted
